=== git-thinh/CSharpTest.Net-source-v2.12.810.409/CSBuild.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="CSBuildConfig" nillable="true" type="CSBuildConfig" />
  <xs:complexType name="CSBuildConfig">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="1" name="target" type="BuildTarget" />
        <xs:element minOccurs="0" maxOccurs="1" name="options" type="BuildOptions" />
        <xs:element minOccurs="0" maxOccurs="1" name="projects" type="ProjectIncludes" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="BuildTarget">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="1" name="add" type="AddProjects" />
        <xs:element minOccurs="0" maxOccurs="1" name="xml" type="XmlFileOutput" />
        <xs:element minOccurs="0" maxOccurs="1" name="framework" type="TargetFramework" />
        <xs:element minOccurs="0" maxOccurs="1" name="log" type="LogFileOutput" />
        <xs:element minOccurs="0" maxOccurs="1" name="intermediateFiles" type="BuildIntermediateFiles" />
        <xs:element minOccurs="0" maxOccurs="1" name="define" type="BuildDefineConst" />
        <xs:element minOccurs="0" maxOccurs="1" name="save-project-changes" type="SaveProjectChanges" />
        <xs:element minOccurs="0" maxOccurs="1" name="remove" type="RemoveProjects" />
        <xs:element minOccurs="0" maxOccurs="1" name="property" type="BuildProperty" />
        <xs:element minOccurs="0" maxOccurs="1" name="output" type="BuildOutput" />
        <xs:element minOccurs="0" maxOccurs="1" name="reference" type="ReferenceFolder" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute default="v3.5" name="tools" type="FrameworkVersions" />
    <xs:attribute default="" name="group" type="xs:string" />
    <xs:attribute default="AnyCPU" name="platform" type="BuildPlatforms" />
    <xs:attribute default="Debug" name="configuration" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="AddProjects">
    <xs:complexContent mixed="false">
      <xs:extension base="BaseFileItem">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="dependsOn" type="DependsUpon" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="BaseFileItem">
    <xs:attribute default="csbuild.exe" name="relative-to" type="OutputRelative" />
    <xs:attribute name="path" type="xs:string" />
  </xs:complexType>
  <xs:simpleType name="OutputRelative">
    <xs:restriction base="xs:string">
      <xs:enumeration value="none" />
      <xs:enumeration value="absolute-path" />
      <xs:enumeration value="csbuild.exe" />
      <xs:enumeration value="working-folder" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ImportOptionsPath">
    <xs:complexContent mixed="false">
      <xs:extension base="BaseFileItem" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="LogFilePath">
    <xs:complexContent mixed="false">
      <xs:extension base="BaseFileItem">
        <xs:attribute default="true" name="enabled" type="xs:boolean" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ReferenceFolder">
    <xs:complexContent mixed="false">
      <xs:extension base="BaseFileItem">
        <xs:attribute default="false" name="recursive" type="xs:boolean" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="BuildOutput">
    <xs:complexContent mixed="false">
      <xs:extension base="BaseFileItem" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="RemoveProjects">
    <xs:complexContent mixed="false">
      <xs:extension base="BaseFileItem" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="BuildIntermediateFiles">
    <xs:complexContent mixed="false">
      <xs:extension base="BaseFileItem" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="BaseFileOutput" abstract="true">
    <xs:complexContent mixed="false">
      <xs:extension base="BaseFileItem">
        <xs:attribute name="level" type="LoggerVerbosity" use="required" />
        <xs:attribute name="file" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="LoggerVerbosity">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Quiet" />
      <xs:enumeration value="Minimal" />
      <xs:enumeration value="Normal" />
      <xs:enumeration value="Detailed" />
      <xs:enumeration value="Diagnostic" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="LogFileOutput">
    <xs:complexContent mixed="false">
      <xs:extension base="BaseFileOutput" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XmlFileOutput">
    <xs:complexContent mixed="false">
      <xs:extension base="BaseFileOutput" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DependsUpon">
    <xs:complexContent mixed="false">
      <xs:extension base="BaseFileItem" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="TargetFramework">
    <xs:attribute name="version" type="FrameworkVersions" use="required" />
  </xs:complexType>
  <xs:simpleType name="FrameworkVersions">
    <xs:restriction base="xs:string">
      <xs:enumeration value="v2.0" />
      <xs:enumeration value="v3.0" />
      <xs:enumeration value="v3.5" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="BuildDefineConst">
    <xs:complexContent mixed="false">
      <xs:extension base="BaseBuildSettingOfString" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="BaseBuildSettingOfString" abstract="true">
    <xs:attribute name="value" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="BuildProperty">
    <xs:complexContent mixed="false">
      <xs:extension base="BaseBuildSettingOfString">
        <xs:attribute default="false" name="global" type="xs:boolean" />
        <xs:attribute name="name" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SaveProjectChanges">
    <xs:attribute name="enabled" type="xs:boolean" use="required" />
    <xs:attribute default="Warning" name="level" type="TraceLevel" />
  </xs:complexType>
  <xs:simpleType name="TraceLevel">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Off" />
      <xs:enumeration value="Error" />
      <xs:enumeration value="Warning" />
      <xs:enumeration value="Info" />
      <xs:enumeration value="Verbose" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="BuildPlatforms">
    <xs:restriction base="xs:string">
      <xs:enumeration value="AnyCPU" />
      <xs:enumeration value="x86" />
      <xs:enumeration value="Itanium" />
      <xs:enumeration value="x64" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="BuildOptions">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="1" name="continue-on-error" type="BuildContinueOnError" />
        <xs:element minOccurs="0" maxOccurs="1" name="logfile" type="LogFilePath" />
        <xs:element minOccurs="0" maxOccurs="1" name="console" type="ConsoleOutputLevel" />
        <xs:element minOccurs="0" maxOccurs="1" name="strict-references" type="BuildStrictReferences" />
        <xs:element minOccurs="0" maxOccurs="1" name="import" type="ImportOptionsPath" />
        <xs:element minOccurs="0" maxOccurs="1" name="global-property" type="BuildProperty" />
        <xs:element minOccurs="0" maxOccurs="1" name="force-file-references" type="ProjectReferencesToFile" />
        <xs:element minOccurs="0" maxOccurs="1" name="save-project-changes" type="SaveProjectChanges" />
        <xs:element minOccurs="0" maxOccurs="1" name="no-standard-references" type="NoStdReferences" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute default="4" name="timeout-hours" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="BuildContinueOnError">
    <xs:complexContent mixed="false">
      <xs:extension base="BooleanBuildOption" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="BooleanBuildOption" abstract="true">
    <xs:attribute default="true" name="enabled" type="xs:boolean" />
  </xs:complexType>
  <xs:complexType name="NoStdReferences">
    <xs:complexContent mixed="false">
      <xs:extension base="BooleanBuildOption" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ProjectReferencesToFile">
    <xs:complexContent mixed="false">
      <xs:extension base="BooleanBuildOption" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="BuildStrictReferences">
    <xs:complexContent mixed="false">
      <xs:extension base="BooleanBuildOption" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ConsoleOutputLevel">
    <xs:complexContent mixed="false">
      <xs:extension base="BaseOutput">
        <xs:attribute default="true" name="enabled" type="xs:boolean" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="BaseOutput" abstract="true">
    <xs:attribute default="Normal" name="level" type="LoggerVerbosity" />
  </xs:complexType>
  <xs:complexType name="ProjectIncludes">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="1" name="remove" type="RemoveProjects" />
        <xs:element minOccurs="0" maxOccurs="1" name="reference" type="ReferenceFolder" />
        <xs:element minOccurs="0" maxOccurs="1" name="add" type="AddProjects" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== git-thinh/CSharpTest.Net-source-v2.12.810.409/Tools/CSBuild/Sample.config.xml
<?xml version="1.0" encoding="utf-8" ?>
<CSBuildConfig xsi:noNamespaceSchemaLocation="CSBuild.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- Global settings and options -->
  <options>
    <!-- Configure the default output level for the console -->
    <console level="Minimal" enabled="true" />
    <!-- Defines the path to the text log file to write for CSBuild logging (not related to MSBuild log) -->
    <logfile path=".\CSBuild.log" relative-to="csbuild.exe"  enabled="false" />
    <!-- Save any changes made to projects, level defines the output type where Error will stop the build -->
    <save-project-changes enabled="false" level="Warning" />
    <!-- Import settings from a text file that contains "Name: Value" or "Name = Value" -->
    <import path="%userprofile%\environment.txt" relative-to="absolute-path" />
    <!-- Specify a single global property that can used in MSBuild or in the paths of this file -->
    <global-property name="MyCustomProperty" value="Value" global="true" />
    <!-- Adds the NoStdLib property to add projects and adds an explicit reference to mscorlib from the reference paths -->
    <no-standard-references enabled="false"/>
    <!-- Enforces that all references come from a reference directory specified in this file -->
    <strict-references enabled="false"/>
    <!-- Changes any Project-to-Project references into file references pointing to that project's primary output -->
    <force-file-references enabled="false"/>
    <!-- When enabled CSBuild will continue building all projects reguardless of how many errors are produced -->
    <continue-on-error enabled="false"/>
  </options>
  <!-- Inclusions and reference directories that apply to all target groups -->
  <projects>
    <!-- Adds all projects recursivly found in this path to all build targets defined below -->    
    <add path=".\src\common" relative-to="csbuild.exe" />
    <!-- Excludes all projects found in this directory, excludes overwrite the add -->
    <remove path=".\src\common\tests" relative-to="csbuild.exe" />
    <!-- Reference assemblies from these directories -->
    <reference path="%SystemRoot%\Microsoft.Net\Framework\v2.0.50727\" relative-to="absolute-path" recursive="false" />
  </projects>
  <!-- Define the .NET 2.0 build, using only 2.0 tools (i.e. Linq will not work) -->
  <target group="v20" tools="v2.0" configuration="Debug" platform="AnyCPU">
    <!-- Set every project's TargetFrameworkVersion to this value, omit to leave alone -->
    <framework version="v2.0"/>
    <!-- Define "FRAMEWORK20" and undefine "FRAMEWORK35" -->
    <define value="FRAMEWORK20;-FRAMEWORK35" />
    <!-- Force all projects to use the same output directory -->
    <output path=".\bin\2.0\$(Configuration)\$(Platform)\obj" relative-to="csbuild.exe" />
    <!-- Force all projects to write intermediate files to this location -->
    <intermediateFiles path=".\bin\2.0\$(Configuration)\$(Platform)\obj\$(AssemblyName)\" relative-to="csbuild.exe"/>
    <!-- Disable the missing comment warning on all projects -->
    <property name="NoWarn" value="1591" global="false" />
    <!-- Set all warnings should be treated as errors -->
    <property name="TreatWarningsAsErrors" value="True" global="false" />
    <!-- Save the changes and fail the build if any of the non-global settings are modified -->
    <save-project-changes enabled="true" level="Error" />
    <!-- Add the projects specific to this target -->
    <add path="src\2.0" relative-to="csbuild.exe" />
    <!-- Remove anything you don't want -->
    <remove path="src\2.0\tests\BrokenNunit\BrokenNunit.csproj" relative-to="csbuild.exe" />
    <!-- Set the log output and detail level desired for text logging -->
    <log relative-to="csbuild.exe" path=".\bin\2.0\$(Configuration)\$(Platform)\msbuild.txt" level="Detailed"/>
    <!-- Set the log output and detail level desired for xml logging -->
    <xml relative-to="csbuild.exe" path=".\bin\2.0\$(Configuration)\$(Platform)\msbuild.xml" level="Normal"/>
  </target>
  <!-- Same thing again for the next target -->
  <target tools="v3.5" configuration="Debug" platform="AnyCPU">
    <framework version="v3.5"/>
    <!-- Allow 3.0/3.5 specific includes -->
    <reference path="%ProgramFiles%\Reference Assemblies\Microsoft\Framework\v3.0\" relative-to="absolute-path" recursive="true"/>
    <reference path="%ProgramFiles%\Reference Assemblies\Microsoft\Framework\v3.5\" relative-to="absolute-path" recursive="true"/>
    <!-- Undefine "FRAMEWORK20" and Define "FRAMEWORK35" -->
    <define value="-FRAMEWORK20;FRAMEWORK35" />
    <!-- Force all projects to use the same output directory -->
    <output path=".\bin\3.5\$(Configuration)\$(Platform)\obj" relative-to="csbuild.exe" />
    <!-- Force all projects to write intermediate files to this location -->
    <intermediateFiles path=".\bin\3.5\$(Configuration)\$(Platform)\obj\$(AssemblyName)\" relative-to="csbuild.exe"/>
    <!-- Disable the missing comment warning on all projects -->
    <property name="NoWarn" value="1591" global="false" />
    <!-- Set all warnings should be treated as errors -->
    <property name="TreatWarningsAsErrors" value="True" global="false" />
    <!-- Don't save project changes -->
    <save-project-changes enabled="false" level="Verbose" />
    <!-- Add the projects specific to this target -->
    <add path="src\3.5" relative-to="csbuild.exe" />
    <!-- Set the log output and detail level desired for text logging -->
    <log relative-to="csbuild.exe" path=".\bin\3.5\$(Configuration)\$(Platform)\msbuild.txt" level="Detailed"/>
    <!-- Set the log output and detail level desired for xml logging -->
    <xml relative-to="csbuild.exe" path=".\bin\3.5\$(Configuration)\$(Platform)\msbuild.xml" level="Normal"/>
  </target>
</CSBuildConfig>
